---
- name: Enable Features
  tags: [api, nxapi, layer3]
  with_items:
    - interface-vlan
  nxos_feature:
    provider: "{{provider}}"
    feature: "{{ item }}"
    state: enabled

- name: Configure Layer 3 Interfaces
  tags: [api, nxapi, layer3]
  with_items: "{{ l3_interfaces }}"
  nxos_interface:
    provider: "{{provider}}"
    interface: "{{ item.interface_type }}{{ item.interface_id }}"
    # mode: layer3
    description: "{{ item.description }}"
    admin_state: up

- name: Ethernet and PortChannel Enable Layer 3
  tags: [api, nxapi, layer3]
  with_items: "{{ l3_interfaces }}"
  when: item.interface_type in ["Ethernet", "PortChannel"]
  nxos_interface:
    provider: "{{provider}}"
    interface: "{{ item.interface_type }}{{ item.interface_id }}"
    mode: layer3


- name: Configure IPv4 Address on Interface
  tags: [api, nxapi, layer3]
  with_items: "{{ l3_interfaces }}"
  nxos_ip_interface:
    provider: "{{provider}}"
    interface: "{{ item.interface_type }}{{ item.interface_id }}"
    version: v4
    addr: "{{ item.ip_address }}"
    mask: "{{ item.prefix }}"
