---
- name: Enable Features
  tags: [api, nxapi, vpc, vlan, trunks]
  with_items:
    # - vpc
    - lacp
  nxos_feature:
    provider: "{{provider}}"
    feature: "{{ item }}"
    state: enabled

- name: Create Port Channels
  tags: [api, nxapi, vpc, vlan, trunks]
  with_items: "{{ portchannels }}"
  nxos_portchannel:
    provider: "{{provider}}"
    group: "{{ item.port_channel_id }}"
    members: "{{ item.members }}"
    force: true
    mode: on
    state: present

- name: Configure Access Switch Port Channels as Trunk
  tags: [api, nxapi, vpc, vlan, trunks]
  with_items: "{{ portchannels }}"
  nxos_switchport:
    provider: "{{provider}}"
    interface: "po{{ item.port_channel_id }}"
    mode: trunk

- name: Enable Port Channel as VPC
  tags: [api, nxapi, vpc, vlan, trunks]
  with_items: "{{ portchannels }}"
  when: item.vpc == true
  nxos_vpc_interface:
    provider: "{{provider}}"
    portchannel: "{{ item.port_channel_id }}"
    vpc: "{{ item.port_channel_id }}"
