---
- name: Enable Features
  tags: [api, nxapi, vpc]
  with_items:
    - vpc
    - lacp
  nxos_feature:
    provider: "{{provider}}"
    feature: "{{ item }}"
    state: enabled

- name: Configure VPC
  tags: [api, nxapi, vpc]
  nxos_vpc:
    provider: "{{provider}}"
    domain: "{{ vpc.domain }}"
    pkl_src: "{{ vpc_pkl_src }}"
    pkl_dest: "{{ vpc_pkl_dest }}"
    pkl_vrf: "{{ vpc.pkl_vrf }}"
    peer_gw: true
    auto_recovery: true

- name: Create Port Channel for VPC
  tags: [api, nxapi, vpc]
  nxos_portchannel:
    provider: "{{provider}}"
    group: "{{ vpc.port_channel.id }}"
    members: "{{ vpc.port_channel.members }}"
    force: true
    mode: on
    state: present

- name: Configure VPC Port Channel Trunk
  tags: [api, nxapi, vpc]
  nxos_switchport:
    provider: "{{provider}}"
    interface: "po{{ vpc.port_channel.id }}"
    mode: trunk

- name: Enable VPC Peer Link on port_channel
  tags: [api, nxapi, vpc]
  nxos_vpc_interface:
    provider: "{{provider}}"
    portchannel: "{{ vpc.port_channel.id }}"
    peer_link: true
