---
- name: Enable NX-API
  tags: [api, nxapi]
  nxos_feature:
    provider: "{{provider}}"
    feature: nxapi
    state: enabled

- name: Enable SNMP
  tags: [api]
  nxos_config:
    provider: "{{provider}}"
    lines:
      - snmp-server community {{ snmp_ro_community | default('public') }} ro
      - snmp-server community {{ snmp_rw_community | default('private') }} rw
      
